#################
### AUTOSTART ###
#################

exec-once = waybar & $cursor

exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-clip-persist --clipboard regular
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = dbus-update-activation-environment --systemd --all
exec-once = gnome-keyring-daemon --start --components=secrets,ssh,pkcs11
exec-once = sleep 3 && secret-tool lookup dummy test >/dev/null 2>&1 || true
exec-once = swww-daemon &
exec-once = swaync
# exec = dunst & 

