###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = kitty -e yazi
$browser = zen-browser
$cursor = hyprctl setcursor "Bibata-Modern-Classic" 28
$messenger = Telegram
$wallpaper = $HOME/.config/rofi/scripts/wallpapermenu.sh
$powermenu = $HOME/.config/rofi/scripts/powermenu.sh
$menu = rofi -show drun

