##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

#windowrule {
#  name = float-dolphin
#  match:initial_class = org\.kde\.dolphin
#  float = on
#  center = on
#  size = 1100 700 
#}

windowrule {
  name = float-telegram
  match:initial_class = org\.telegram\.desktop
  float = on
  center = on
  size = 700 900
}

windowrule {
  name = float-openrgb
  match:initial_class = org\.openrgb\.OpenRGB
  float = on
  center = on
  size = 920 600
}

windowrule {
  name = float-pavucontrol
  match:initial_class = org\.pulseaudio\.pavucontrol
  float = on
  center = on
  size = 700 500
}

windowrule {
  name = float-obsidian
  match:initial_class = obsidian
  float = on
  center = on
  size = 1100 800
}

windowrule {
  name = float-audiorelay
  match:initial_class = com-azefsw-audioconnect-desktop-app-MainKt
  float = on
  center = on
 }

windowrule {
  name = float-thunar
  match:initial_class = thunar
  float = on
  center = on
  size = 1100 700
 }

#windowrule {
#  name = float-loupe
#  match:initial_class = org\.gnome\.Loupe
#  float = on
#  center = on
# }

windowrule {
  name = fix-android-studio-popups
  match:class = jetbrains-studio
  match:title = ^win(.*)$
  no_initial_focus = on
}


layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.48, match:namespace swaync-control-center

layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.35, match:namespace swaync-notification-window

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }

