# Папки
/home/ghostik/Documents/Obsidian Vaults=gdrive:Obsidian Vaults
/home/ghostik/Univer=gdrive:Univer
/home/ghostik/Documents/Somethings=gdrive:Somethings

# Отдельные файлы
/home/ghostik/.local/share/millennium/plugins/non-steam-playtimes/sessions.json=gdrive:Somethings/Millennium

# Дополнительные папки
/home/ghostik/Games/factorio/saves=gdrive:Somethings/Saves/Factorio_2.0.76(Linux)
